var timeline_data = {
'dateTimeFormat': 'iso8601',
'events' : [
	{'start': '1870',
	 'end': '1911',
	 'title': 'Lestadiolaisuuden tulo ja alkuvaiheet',
	 'description' : '',
	 'isInstant' : true,
	 'color': 'green'
	},
	{'start': '1911',
	 'end': '1945',
	 'title': 'Rauhanyhdistyksen perustaminen tuo j�ntevyytt�',
	 'description' : '',
	 'isInstant' : true,
	 'color': 'blue'
	},
	{'start': '1945',
	 'end': '1974',
	 'title': 'Aktiivista toimintaa ja j�lleenrakennusty�t�',
	 'description' : '',
	 'isInstant' : true,
	 'color': 'gray'
	},
	{'start': '1974',
	 'end': '2011',
	 'title': 'Vilkas yhdistys Taulum�ell�',
	 'description' : '',
	 'isInstant' : true,
	 'color': 'red'
	},
	{'start': '1900-01-01',
	'title': 'Aleksis Juhonpoika Reiju',
	'description': 'Muurari Aleksis Juhonpoika Reiju, Arvo ja Vilho Reijun isä (Vilho Reijun albumi)',
	'image': '../thumbnails/thumb.1900isareiju.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1900isareiju.jpg'
	},
	{'start': '1900-01-01',
	'title': 'Tyynelä Keljossa, Ida Oksasen mökki',
	'description': 'Tyynelän talo, jossa uskovaiset kävivät paljon. Mökki testamentattiin rauhanyhdistykselle.',
	'image': '../thumbnails/thumb.1900tyynela keljo.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1900tyynela keljo.jpg'
	},
	{'start': '1910-01-01',
	'title': 'Ellen Helena Reiju poikineen',
	'description': 'keskellä Juho Vilho Reiju (s.1908) ja Arvo Aleksius Reiju (s. 1895)',
	'image': '../thumbnails/thumb.1910reijuperhe.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1910reijuperhe.jpg'
	},
	{'start': '1920-01-01',
	'title': 'Arvo Reiju, faktori. Toiminut sananpalvelijana useita vuosia.',
	'description': 'Arvo Reiju, faktori. Toiminut sananpalvelijana useita vuosia.',
	'image': '../thumbnails/thumb.1920puh ArvoReiju.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1920puh ArvoReiju.jpg'
	},
	{'start': '1920-01-01',
	'title': 'Rauha ja Kaarlo Metsä',
	'description': 'Rauha ja Kaarlo Metsä lastensa Maj-Lisin (Piekänen) ja Olavin (vas.) kanssa. Rauha Metsä oli Opistokujalla vahtimestarina.',
	'image': '../thumbnails/thumb.1920perhmetsa00202.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1920perhmetsa00202.jpg'
	},
	{'start': '1920-02-01',
	'title': 'Otto ja Olga Hokkanen',
	'description': 'Sananpalvelija Otto Hokkanen puolisonsa Olgan kanssa',
	'image': '../thumbnails/thumb.1920HenkHokkanen0601.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1920HenkHokkanen0601.jpg'
	},
	{'start': '1920-05-01',
	'title': 'Oittisen talo Vapaudenkatu 40. Tämän talon piharakennuksessa on pidetty seuroja.',
	'description': 'Oittisen talo Vapaudenkatu 40. Tämän talon  piharakennuksessa on pidetty seuroja pitkään.',
	'image': '../thumbnails/thumb.1920seurtalo0662.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1920seurtalo0662.jpg'
	},
	{'start': '1920-06-15',
	'title': 'Tämä kuva on otettu kesällä 1927. Kahvia paahdettiin seppä Turpeisen pajassa ja kahvit jauhettiin pihalla talkoilla isoja seuroja varten."',
	'description': 'Vas. istuva mies Usko Gröndahl, seur. Kasper Taipale, Hilda Oksanen, Saima Kuoppala, Mari Tantanen lapsi sylissä. Oikealla tumma asuinen mies Siekkinen (esilaulaja seuroissa), hänen yläp. Hugo Linnanto.',
	'image': '../thumbnails/thumb.1920taital00330.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1920taital00330.jpg'
	},
	{'start': '1921-01-01',
	'title': 'Tekla Nylund',
	'description': 'Tekla Nylund, yhdistyksen pitkäaikainen sihteeri.',
	'image': '../thumbnails/thumb.1921teklanylund.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1921teklanylund.jpg'
	},
	{'start': '1923-07-01',
	'title': 'Jyväskylän kirjastotalo, jossa vuosina 1922-1923 pidettiin seuroja',
	'description': 'Jyväskylän kirjastotalo, jossa vuosina 1922-1923 pidettiin seuroja',
	'image': '../thumbnails/thumb.1923seupaikka0607.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1923seupaikka0607.jpg'
	},
	{'start': '1924-06-01',
	'title': 'Hongikontie 1 tontilla aiemmin ollut talo',
	'description': 'Hongikontie 1 tontilla aiemmin ollut talo, palanut 1924.(Vilho Reijun albumi)',
	'image': '../thumbnails/thumb.1924seurak001.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1924seurak001.jpg'
	},
	{'start': '1925-03-01',
	'title': 'Ompeluseurat Hännisellä Kauppakadulla',
	'description': 'Seisomassa vas. Arvo Reiju, Paavo Laitinen, David Kosunen, Kalle Marjanen. Istumassa vas. Hjalmar Mantere, Hannes Turpeinen, Martti Tammikari, Hannes Oksanen, Hänninen.',
	'image': '../thumbnails/thumb.1925seuomp0501.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1925seuomp0501.jpg'
	},
	{'start': '1925-03-01',
	'title': 'Ompeluseurat Hännisellä Kauppakadulla',
	'description': 'Takarivissä vas.Hanna Valkonen, Martta Marjanen, Rauha Metsä, Hilda Oksanen, Tekla Laitinen, Helmi Jylhä, Edith Turpeinen ja tuntematon. Eturivissä vas. Saima Mantere, Flora Blomqvist, tuntematon, Hilda Kauppinen, Lyyli Kauppinen ja tuntematon. Lapsi tuntematon.',
	'image': '../thumbnails/thumb.1925seuomp0502.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1925seuomp0502.jpg'
	},
	{'start': '1925-08-01',
	'title': 'seuroissa Salmisella Vaajakoskella',
	'description': 'Oik. Riikka ja Stefaanus Kytölä, Aini ja Kalle Salminen, Hanna Valkonen (myöh Vuorela), Eeva Kaihlaniemi, Lyydia Lofman (myöh. Orenius), Kasper Taipale, Emmi Holopainen (myöh. Gröndahl), Maria Rantanen ja tytär (ehkä v. 1925)',
	'image': '../thumbnails/thumb.1925ryh0608.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1925ryh0608.jpg'
	},
	{'start': '1927-07-08',
	'title': 'Isot seurat Jyväskylässä Lounaispuistossa vuonna 1927.',
	'description': 'Isot seurat Jyväskylässä Lounaispuistossa vuonna 1927.',
	'image': '../thumbnails/thumb.1927seur0802.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1927seur0802.jpg'
	},
	{'start': '1927-07-08',
	'title': 'Vuoden 1927 isojen seurojen osallistujia, järjestäjiä ja puhujia Harjun portailla Jyväskylässä',
	'description': 'Vuoden 1927 isojen seurojen osallistujia, järjestäjiä ja puhujia Harjun portailla',
	'image': '../thumbnails/thumb.1927seur0814.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1927seur0814.jpg'
	},
	{'start': '1927-07-08',
	'title': 'isot seurat Jyväskylässä 1927',
	'description': 'Seuraväkeä suviseuroissa 1927',
	'image': '../thumbnails/thumb.1927Seu0602.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1927Seu0602.jpg'
	},
	{'start': '1927-07-08',
	'title': 'Isot seurat Jyväskylässä vuonna 1927',
	'description': 'Isot seurat Jyväskylässä vuonna 1927 Vas. Rauha Metsä, Hilda Oksanen, Ida Oksanen, Hulda Kelander ja Lempi Kotiranta',
	'image': '../thumbnails/thumb.1927Seuryh0603.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1927Seuryh0603.jpg'
	},
	{'start': '1929-06-01',
	'title': 'Reijun talo Keljossa',
	'description': 'Reijun kotitalo Keljossa, kuvatekstinä: KOTIKOIVUN VARJOSSA.Koivuun nojaa Arvo Reiju  (Vilho Reijun albumi)',
	'image': '../thumbnails/thumb.1929reijuntalo keljo.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1929reijuntalo keljo.jpg'
	},
	{'start': '1930-01-01',
	'title': 'Tyyne ja Daavid Kosunen ja lapset',
	'description': 'Tyyne ja David Kosunen ja lapset, Tyyne Kosunen oli johtokunnassa kahdesti',
	'image': '../thumbnails/thumb.1930perhkosunen00201.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1930perhkosunen00201.jpg'
	},
	{'start': '1930-01-01',
	'title': 'Ellen Helena Reiju',
	'description': 'Ellen Helena Reiju',
	'image': '../thumbnails/thumb.1930reiju aiti.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1930reiju aiti.jpg'
	},
	{'start': '1930-01-01',
	'title': 'Saarnaaja Junno Rautio ja Karoliina',
	'description': 'Saarnaaja Junno Rautio ja vaimonsa Karoliina',
	'image': '../thumbnails/thumb.1930henkRautio0809.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1930henkRautio0809.jpg'
	},
	{'start': '1930-03-01',
	'title': 'Rauha ja Kaarlo Metsän perhe',
	'description': 'Rauha ja Kaarlo Metsän perhe',
	'image': '../thumbnails/thumb.1930perhmetsa00300.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1930perhmetsa00300.jpg'
	},
	{'start': '1930-06-25',
	'title': 'Jyväskylän juhannuseurojen 1930 ruokalakatos',
	'description': 'Jyväskylän juhannuseurojen 1930 ruokalakatos',
	'image': '../thumbnails/thumb.1930seury161.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1930seury161.jpg'
	},
	{'start': '1930-07-01',
	'title': 'Väkeä Tuomiojärvellä 1930-luvulla',
	'description': 'Väkeä Tuomiojärvellä 1930-luvulla',
	'image': '../thumbnails/thumb.1930ret3002.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1930ret3002.jpg'
	},
	{'start': '1930-07-01',
	'title': 'Majamäen pihapiiri',
	'description': 'Majamäen talon pihapiiri kesällä 1900-luvun alkupuolella (Vilho Reijun albumi)',
	'image': '../thumbnails/thumb.1900majamaki2.jpg',
	'icon': 'images/dark-green-circle.png',
	'link': '../files/1900majamaki2.jpg'
	}

]
}
var TIMELINE_START = new Date(Date.UTC(1900, 0, 1));
var TIMELINE_STOP = new Date(Date.UTC(1935, 0, 1));
